# Generated by OmopViewer 0.1.0
# Be careful editing this file

library(bslib)
library(dplyr)
library(DT)
library(gt)
library(here)
library(OmopSketch)
library(OmopViewer)
library(readr)
library(shiny)
library(visOmopResults)

data_file<-list.files(here("data"), recursive = TRUE,
                    full.names = TRUE)

results_file<-data_file[stringr::str_detect(data_file, ".csv")]
results_file<-results_file[stringr::str_detect(results_file, "result")]
results <- list()
for(i in seq_along(results_file)){
  results[[i]]<-omopgenerics::importSummarisedResult(path=results_file[[i]])
 
}
data <- dplyr::bind_rows(results) |>OmopViewer::correctSettings()

