# Generated by OmopViewer 0.1.0
# Be careful editing this file

library(bslib)
library(dplyr)
library(DT)
library(gt)
library(here)
library(OmopSketch)
library(OmopViewer)
library(readr)
library(shiny)
library(visOmopResults)

data_file<-list.files(here::here("data"), recursive = TRUE,
                    full.names = TRUE)

data_file<-data_file[stringr::str_detect(data_file, ".csv")]
results_file<-data_file[stringr::str_detect(data_file, "characterisation")]
results <- list()
for(i in seq_along(results_file)){
  results[[i]]<-omopgenerics::importSummarisedResult(path=results_file[[i]])
 
}
data <- dplyr::bind_rows(results) |>OmopViewer::correctSettings()

bm_file<-data_file[stringr::str_detect(data_file, "timing")]
bm <- list()
for(i in seq_along(bm_file)){
  bm[[i]]<-read.csv(bm_file[[i]])
  
}
bm <- dplyr::bind_rows(bm)
bm
