# Generated by OmopViewer 0.2.0
# Be careful editing this file

server <- function(input, output, session) {
  # download raw data -----
  output$download_raw <- shiny::downloadHandler(
    filename = "results.csv",
    content = function(file) {
      omopgenerics::exportSummarisedResult(data, fileName = file)
    }
  )
  # summarise_omop_snapshot -----
  ## tidy summarise_omop_snapshot -----
  getTidyDataSummariseOmopSnapshot <- shiny::reactive({
    res <- data |>
      filterData("summarise_omop_snapshot", input) |>
      omopgenerics::addSettings() |>
      omopgenerics::splitAll() |>
      dplyr::select(!"result_id")

    # columns to eliminate
    colsEliminate <- colnames(res)
    colsEliminate <- colsEliminate[!colsEliminate %in% c(
      input$summarise_omop_snapshot_tidy_columns, "variable_name", "variable_level",
      "estimate_name", "estimate_type", "estimate_value"
    )]

    # pivot
    pivot <- input$summarise_omop_snapshot_tidy_pivot
    if (pivot != "none") {
      vars <- switch(pivot,
        "estimates" = "estimate_name",
        "estimates and variables" = c("variable_name", "variable_level", "estimate_name")
      )
      res <- res |>
        visOmopResults::pivotEstimates(pivotEstimatesBy = vars)
    }

    res |>
      dplyr::select(!dplyr::all_of(colsEliminate))
  })
  output$summarise_omop_snapshot_tidy <- DT::renderDT({
    DT::datatable(
      getTidyDataSummariseOmopSnapshot(),
      options = list(scrollX = TRUE),
      rownames = FALSE
    )
  })
  output$summarise_omop_snapshot_tidy_download <- shiny::downloadHandler(
    filename = "tidy_summarise_omop_snapshot.csv",
    content = function(file) {
      getTidyDataSummariseOmopSnapshot() |>
        readr::write_csv(file = file)
    }
  )
  ## output summarise_omop_snapshot -----
  ## output 17 -----
  createOutput17 <- shiny::reactive({
    result <- data |>
      filterData("summarise_omop_snapshot", input)
    OmopSketch::tableOmopSnapshot(
      result
    )
  })
  output$summarise_omop_snapshot_gt_17 <- gt::render_gt({
    createOutput17()
  })
  output$summarise_omop_snapshot_gt_17_download <- shiny::downloadHandler(
    filename = paste0("output_gt_summarise_omop_snapshot.", input$summarise_omop_snapshot_gt_17_download_type),
    content = function(file) {
      obj <- createOutput17()
      gt::gtsave(data = obj, filename = file)
    }
  )


  # summarise_characteristics -----
  ## tidy summarise_characteristics -----
  getTidyDataSummariseCharacteristics <- shiny::reactive({
    res <- data |>
      filterData("summarise_characteristics", input) |>
      omopgenerics::addSettings() |>
      omopgenerics::splitAll() |>
      dplyr::select(!"result_id")

    # columns to eliminate
    colsEliminate <- colnames(res)
    colsEliminate <- colsEliminate[!colsEliminate %in% c(
      input$summarise_characteristics_tidy_columns, "variable_name", "variable_level",
      "estimate_name", "estimate_type", "estimate_value"
    )]

    # pivot
    pivot <- input$summarise_characteristics_tidy_pivot
    if (pivot != "none") {
      vars <- switch(pivot,
        "estimates" = "estimate_name",
        "estimates and variables" = c("variable_name", "variable_level", "estimate_name")
      )
      res <- res |>
        visOmopResults::pivotEstimates(pivotEstimatesBy = vars)
    }

    res |>
      dplyr::select(!dplyr::all_of(colsEliminate))
  })
  output$summarise_characteristics_tidy <- DT::renderDT({
    DT::datatable(
      getTidyDataSummariseCharacteristics(),
      options = list(scrollX = TRUE),
      rownames = FALSE
    )
  })
  output$summarise_characteristics_tidy_download <- shiny::downloadHandler(
    filename = "tidy_summarise_characteristics.csv",
    content = function(file) {
      getTidyDataSummariseCharacteristics() |>
        readr::write_csv(file = file)
    }
  )
  ## output summarise_characteristics -----
  ## output 7 -----


  createOutput7 <- shiny::reactive({
    result <- data |>
      filterData("summarise_characteristics", input) 
    
    header <- input$summarise_characteristics_gt_7_header
    groupColumn <- input$summarise_characteristics_gt_7_groupColumn
    hide <- input$summarise_characteristics_gt_7_hide
    
    if (is.null(header) || length(header) == 0) header <- c("cdm_name")
    if (is.null(groupColumn) || length(groupColumn) == 0) groupColumn <- c("cohort_name", "sex", "age_group")
    if (is.null(hide) || length(hide) == 0) hide <- c("table_name")
    
    CohortCharacteristics::tableCharacteristics(
      result,
      header = header,
      groupColumn = groupColumn,
      hide = hide
    )
  })
  output$summarise_characteristics_gt_7 <- gt::render_gt({
    createOutput7()
  })
  output$summarise_characteristics_gt_7_download <- shiny::downloadHandler(
    filename = paste0("output_gt_summarise_characteristics.", input$summarise_characteristics_gt_7_download_type),
    content = function(file) {
      obj <- createOutput7()
      gt::gtsave(data = obj, filename = file)
    }
  )

  ## output 8 -----
  createOutput8 <- shiny::reactive({
    result <- data |>
      filterData("summarise_characteristics", input)
    result <- result |> dplyr::filter(.data$variable_name == input$summarise_characteristics_ggplot2_8_variableName)
    CohortCharacteristics::plotCharacteristics(
      result,
      plotStyle = input$summarise_characteristics_ggplot2_8_plotStyle,
      facet = input$summarise_characteristics_ggplot2_8_facet,
      colour = input$summarise_characteristics_ggplot2_8_colour
    ) + ggplot2::theme(axis.text.x = element_text(angle = 90, hjust = 1))
  })
  output$summarise_characteristics_ggplot2_8 <- shiny::renderPlot({
    createOutput8()
  })
  output$summarise_characteristics_ggplot2_8_download <- shiny::downloadHandler(
    filename = paste0("output_ggplot2_summarise_characteristics.", "png"),
    content = function(file) {
      obj <- createOutput8()
      ggplot2::ggsave(
        filename = file,
        plot = obj,
        width = as.numeric(input$summarise_characteristics_ggplot2_8_download_width),
        height = as.numeric(input$summarise_characteristics_ggplot2_8_download_height),
        units = input$summarise_characteristics_ggplot2_8_download_units,
        dpi = as.numeric(input$summarise_characteristics_ggplot2_8_download_dpi)
      )
    }
  )


  # summarise_missing_data -----
  ## tidy summarise_missing_data -----
  getTidyDataSummariseMissingData <- shiny::reactive({
    res <- data |>
      filterData("summarise_missing_data", input) |>
      omopgenerics::addSettings() |>
      omopgenerics::splitAll() |>
      dplyr::select(!"result_id")

    # columns to eliminate
    colsEliminate <- colnames(res)
    colsEliminate <- colsEliminate[!colsEliminate %in% c(
      input$summarise_missing_data_tidy_columns, "variable_name", "variable_level",
      "estimate_name", "estimate_type", "estimate_value"
    )]

    # pivot
    pivot <- input$summarise_missing_data_tidy_pivot
    if (pivot != "none") {
      vars <- switch(pivot,
        "estimates" = "estimate_name",
        "estimates and variables" = c("variable_name", "variable_level", "estimate_name")
      )
      res <- res |>
        visOmopResults::pivotEstimates(pivotEstimatesBy = vars)
    }

    res |>
      dplyr::select(!dplyr::all_of(colsEliminate))
  })
  output$summarise_missing_data_tidy <- DT::renderDT({
    DT::datatable(
      getTidyDataSummariseMissingData(),
      options = list(scrollX = TRUE),
      rownames = FALSE
    )
  })
  output$summarise_missing_data_tidy_download <- shiny::downloadHandler(
    filename = "tidy_summarise_missing_data.csv",
    content = function(file) {
      getTidyDataSummariseMissingData() |>
        readr::write_csv(file = file)
    }
  )
  # ## output summarise_missing_data -----
  ## output 0 -----
  createOutput26 <- shiny::reactive({
    result <- data |>
      filterData("summarise_missing_data", input)|>
      dplyr::arrange(.data$strata_level)
    header <- input$summarise_missing_data_gt_0_header
    group <- input$summarise_missing_data_gt_0_group
    hide <- input$summarise_missing_data_gt_0_hide
    
    if (is.null(header) || length(header) == 0) header <- c("cdm_name")
    if (is.null(group) || length(group) == 0) group <- c("omop_table","year")
    if (is.null(hide) || length(hide) == 0) hide <- c(	"study_period_end",	"study_period_start", "variable_level")
    simpleTable(
      result,
      header = header,
      group = group,
      hide = hide
    )
  })
  output$summarise_missing_data_gt_0 <- gt::render_gt({
    createOutput26()
  })
  output$summarise_missing_data_gt_0_download <- shiny::downloadHandler(
    filename = paste0("output_gt_summarise_missing_data.", input$summarise_missing_data_gt_0_download_type),
    content = function(file) {
      obj <- createOutput26()
      gt::gtsave(data = obj, filename = file)
    }
  )


  # summarise_all_concept_counts -----
  ## tidy summarise_all_concept_counts -----
  getTidyDataSummariseAllConceptCounts <- shiny::reactive({
    res <- data |>
      filterData("summarise_all_concept_counts", input) |>
      omopgenerics::addSettings() |>
      omopgenerics::splitAll() |>
      dplyr::select(!"result_id")

    # columns to eliminate
    colsEliminate <- colnames(res)
    colsEliminate <- colsEliminate[!colsEliminate %in% c(
      input$summarise_all_concept_counts_tidy_columns, "variable_name", "variable_level",
      "estimate_name", "estimate_type", "estimate_value"
    )]

    # pivot
    pivot <- input$summarise_all_concept_counts_tidy_pivot
    if (pivot != "none") {
      vars <- switch(pivot,
        "estimates" = "estimate_name",
        "estimates and variables" = c("variable_name", "variable_level", "estimate_name")
      )
      res <- res |>
        visOmopResults::pivotEstimates(pivotEstimatesBy = vars)
    }

    res |>
      dplyr::select(!dplyr::all_of(colsEliminate))
  })
  output$summarise_all_concept_counts_tidy <- DT::renderDT({
    DT::datatable(
      getTidyDataSummariseAllConceptCounts(),
      options = list(scrollX = TRUE),
      rownames = FALSE
    )
  })
  output$summarise_all_concept_counts_tidy_download <- shiny::downloadHandler(
    filename = "tidy_summarise_all_concept_counts.csv",
    content = function(file) {
      getTidyDataSummariseAllConceptCounts() |>
        readr::write_csv(file = file)
    }
  )
  ## output summarise_all_concept_counts -----
  ## output 0 -----
  createOutput27 <- shiny::reactive({
    result <- data |>
      filterData("summarise_all_concept_counts", input)
    header <- input$summarise_all_concept_counts_gt_0_header
    group <- input$summarise_all_concept_counts_gt_0_group
    hide <- input$summarise_all_concept_counts_gt_0_hide
    
    if (is.null(header) || length(header) == 0) header <- c("cdm_name")
    if (is.null(group) || length(group) == 0) group <- c("omop_table","year")
    if (is.null(hide) || length(hide) == 0) hide <- c("study_period_end",	"study_period_start")
    simpleTable(
      result,
      header = header,
      group = group,
      hide = hide
    )
  })
  output$summarise_all_concept_counts_gt_0 <- gt::render_gt({
    createOutput27()
  })
  output$summarise_all_concept_counts_gt_0_download <- shiny::downloadHandler(
    filename = paste0("output_gt_summarise_all_concept_counts.", input$summarise_all_concept_counts_gt_0_download_type),
    content = function(file) {
      obj <- createOutput27()
      gt::gtsave(data = obj, filename = file)
    }
  )


  # summarise_clinical_records -----
  ## tidy summarise_clinical_records -----
  getTidyDataSummariseClinicalRecords <- shiny::reactive({
    res <- data |>
      filterData("summarise_clinical_records", input) |>
      omopgenerics::addSettings() |>
      omopgenerics::splitAll() |>
      dplyr::select(!"result_id")

    # columns to eliminate
    colsEliminate <- colnames(res)
    colsEliminate <- colsEliminate[!colsEliminate %in% c(
      input$summarise_clinical_records_tidy_columns, "variable_name", "variable_level",
      "estimate_name", "estimate_type", "estimate_value"
    )]

    # pivot
    pivot <- input$summarise_clinical_records_tidy_pivot
    if (pivot != "none") {
      vars <- switch(pivot,
        "estimates" = "estimate_name",
        "estimates and variables" = c("variable_name", "variable_level", "estimate_name")
      )
      res <- res |>
        visOmopResults::pivotEstimates(pivotEstimatesBy = vars)
    }

    res |>
      dplyr::select(!dplyr::all_of(colsEliminate))
  })
  output$summarise_clinical_records_tidy <- DT::renderDT({
    DT::datatable(
      getTidyDataSummariseClinicalRecords(),
      options = list(scrollX = TRUE),
      rownames = FALSE
    )
  })
  output$summarise_clinical_records_tidy_download <- shiny::downloadHandler(
    filename = "tidy_summarise_clinical_records.csv",
    content = function(file) {
      getTidyDataSummariseClinicalRecords() |>
        readr::write_csv(file = file)
    }
  )
  ## output summarise_clinical_records -----
  ## output 0 -----
  # createOutput22 <- shiny::reactive({
  #   result <- data |>
  #     filterData("summarise_clinical_records", input)
  #   
  #   header <- input$summarise_clinical_records_gt_0_header
  #   group <- input$summarise_clinical_records_gt_0_group
  #   hide <- input$summarise_clinical_records_gt_0_hide
  #   
  #   if (is.null(header) || length(header) == 0) header <- c("cdm_name")
  #   if (is.null(group) || length(group) == 0) group <- c()
  #   if (is.null(hide) || length(hide) == 0) hide <- c()
  #   
  #   simpleTable(
  #     result,
  #     header = header,
  #     group = group,
  #     hide = hide
  #   )
  # })
  # output$summarise_clinical_records_gt_0 <- gt::render_gt({
  #   createOutput22()
  # })
  # output$summarise_clinical_records_gt_0_download <- shiny::downloadHandler(
  #   filename = paste0("output_gt_summarise_clinical_records.", input$summarise_clinical_records_gt_0_download_type),
  #   content = function(file) {
  #     obj <- createOutput22()
  #     gt::gtsave(data = obj, filename = file)
  #   }
  # )
  createOutput21 <- shiny::reactive({
    res <- data |>
      filterData("summarise_clinical_records", input)
    OmopSketch::tableClinicalRecords(res)
  })
  output$summarise_clinical_records_gt_15 <- gt::render_gt({
    createOutput21()
  })
  output$summarise_clinical_records_gt_15_download <- shiny::downloadHandler(
    filename = paste0("output_gt_summarise_clinical_records.", input$summarise_clinical_records_gt_15_download_type),
    content = function(file) {
      obj <- createOutput21()
      gt::gtsave(data = obj, filename = file)
    }
  )
  
  

  # summarise_record_count -----
  ## tidy summarise_record_count -----
  getTidyDataSummariseRecordCount <- shiny::reactive({
    res <- data |>
      filterData("summarise_record_count", input) |>
      omopgenerics::addSettings() |>
      omopgenerics::splitAll() |>
      dplyr::select(!"result_id")

    # columns to eliminate
    colsEliminate <- colnames(res)
    colsEliminate <- colsEliminate[!colsEliminate %in% c(
      input$summarise_record_count_tidy_columns, "variable_name", "variable_level",
      "estimate_name", "estimate_type", "estimate_value"
    )]

    # pivot
    pivot <- input$summarise_record_count_tidy_pivot
    if (pivot != "none") {
      vars <- switch(pivot,
        "estimates" = "estimate_name",
        "estimates and variables" = c("variable_name", "variable_level", "estimate_name")
      )
      res <- res |>
        visOmopResults::pivotEstimates(pivotEstimatesBy = vars)
    }

    res |>
      dplyr::select(!dplyr::all_of(colsEliminate))
  })
  output$summarise_record_count_tidy <- DT::renderDT({
    DT::datatable(
      getTidyDataSummariseRecordCount(),
      options = list(scrollX = TRUE),
      rownames = FALSE
    )
  })
  output$summarise_record_count_tidy_download <- shiny::downloadHandler(
    filename = "tidy_summarise_record_count.csv",
    content = function(file) {
      getTidyDataSummariseRecordCount() |>
        readr::write_csv(file = file)
    }
  )
  ## output summarise_record_count -----
  ## output 0 -----
  createOutput23 <- shiny::reactive({
    result <- data |>
      filterData("summarise_record_count", input)|>
      dplyr::arrange(.data$additional_level)
    header <- input$summarise_record_count_gt_0_header
    group <- input$summarise_record_count_gt_0_group
    hide <- input$summarise_record_count_gt_0_hide
    
    if (is.null(header) || length(header) == 0) header <- c("cdm_name")
    if (is.null(group) || length(group) == 0) group <- c("omop_table", "sex", "age_group")
    if (is.null(hide) || length(hide) == 0) hide <- c("interval",	"study_period_end",	"study_period_start", "variable_level",	"estimate_name")
    simpleTable(
      result,
      header = header,
      group = group,
      hide = hide
    )
  })
  output$summarise_record_count_gt_0 <- gt::render_gt({
    createOutput23()
  })
  output$summarise_record_count_gt_0_download <- shiny::downloadHandler(
    filename = paste0("output_gt_summarise_record_count.", input$summarise_record_count_gt_0_download_type),
    content = function(file) {
      obj <- createOutput23()
      gt::gtsave(data = obj, filename = file)
    }
  )

  createOutput18 <- shiny::reactive({
    result <- data |>
      filterData("summarise_record_count", input)
    OmopSketch::plotRecordCount(
      result,
      facet = input$summarise_record_count_ggplot2_16_facet, 
      colour = input$summarise_record_count_ggplot2_16_colour
    )
  })
  output$summarise_record_count_ggplot2_16 <- shiny::renderPlot({
    createOutput18()
  })
  output$summarise_record_count_ggplot2_16_download <- shiny::downloadHandler(
    filename = paste0("output_ggplot2_summarise_record_count.", "png"),
    content = function(file) {
      obj <- createOutput18()
      ggplot2::ggsave(
        filename = file,
        plot = obj,
        width = as.numeric(input$summarise_record_count_ggplot2_16_download_width),
        height = as.numeric(input$summarise_record_count_ggplot2_16_download_height),
        units = input$summarise_record_count_ggplot2_16_download_units,
        dpi = as.numeric(input$summarise_record_count_ggplot2_16_download_dpi)
      )
    }
  )
  

  # summarise_in_observation -----
  ## tidy summarise_in_observation -----
  getTidyDataSummariseInObservation <- shiny::reactive({
    res <- data |>
      filterData("summarise_in_observation", input) |>
      omopgenerics::addSettings() |>
      omopgenerics::splitAll() |>
      dplyr::select(!"result_id")

    # columns to eliminate
    colsEliminate <- colnames(res)
    colsEliminate <- colsEliminate[!colsEliminate %in% c(
      input$summarise_in_observation_tidy_columns, "variable_name", "variable_level",
      "estimate_name", "estimate_type", "estimate_value"
    )]

    # pivot
    pivot <- input$summarise_in_observation_tidy_pivot
    if (pivot != "none") {
      vars <- switch(pivot,
        "estimates" = "estimate_name",
        "estimates and variables" = c("variable_name", "variable_level", "estimate_name")
      )
      res <- res |>
        visOmopResults::pivotEstimates(pivotEstimatesBy = vars)
    }

    res |>
      dplyr::select(!dplyr::all_of(colsEliminate))
  })
  output$summarise_in_observation_tidy <- DT::renderDT({
    DT::datatable(
      getTidyDataSummariseInObservation(),
      options = list(scrollX = TRUE),
      rownames = FALSE
    )
  })
  output$summarise_in_observation_tidy_download <- shiny::downloadHandler(
    filename = "tidy_summarise_in_observation.csv",
    content = function(file) {
      getTidyDataSummariseInObservation() |>
        readr::write_csv(file = file)
    }
  )
  ## output summarise_in_observation -----
  ## output 0 -----
  createOutput0 <- shiny::reactive({
    result <- data |>
      filterData("summarise_in_observation", input)
    
    header <- input$summarise_in_observation_gt_0_header
    group <- input$summarise_in_observation_gt_0_group
    hide <- input$summarise_in_observation_gt_0_hide
    
    if (is.null(header) || length(header) == 0) header <- c("cdm_name")
    if (is.null(group) || length(group) == 0) group <- c("sex", "age_group")
    if (is.null(hide) || length(hide) == 0) hide <- c("omop_table", "interval",	"study_period_end",	"study_period_start", "variable_level")
    simpleTable(
      result,
      header = header,
      group = group,
      hide = hide
    )
  })
  output$summarise_in_observation_gt_0 <- gt::render_gt({
    createOutput0()
  })
  output$summarise_in_observation_gt_0_download <- shiny::downloadHandler(
    filename = paste0("output_gt_summarise_in_observation.", input$summarise_in_observation_gt_0_download_type),
    content = function(file) {
      obj <- createOutput0()
      gt::gtsave(data = obj, filename = file)
    }
  )

  createOutput19 <- shiny::reactive({
    result <- data |>
      filterData("summarise_in_observation", input)
    result <- result |> dplyr::filter(.data$variable_name == input$summarise_in_observation_ggplot2_19_variableName)
    OmopSketch::plotInObservation(
      result,
      facet = input$summarise_in_observation_ggplot2_19_facet,
      colour = input$summarise_in_observation_ggplot2_19_colour
    )
  })
  
  # Render the plot in the UI
  output$summarise_in_observation_ggplot2_19 <- shiny::renderPlot({
    createOutput19()
  })
  
  # Provide download handler for saving plot
  output$summarise_in_observation_ggplot2_19_download <- shiny::downloadHandler(
    filename = "output_ggplot2_summarise_in_observation.png",
    content = function(file) {
      obj <- createOutput19()
      ggplot2::ggsave(
        filename = file,
        plot = obj,
        width = as.numeric(input$summarise_in_observation_ggplot2_19_download_width),
        height = as.numeric(input$summarise_in_observation_ggplot2_19_download_height),
        units = input$summarise_in_observation_ggplot2_19_download_units,
        dpi = as.numeric(input$summarise_in_observation_ggplot2_19_download_dpi)
      )
    }
  )

  # summarise_observation_period -----
  ## tidy summarise_observation_period -----
  getTidyDataSummariseObservationPeriod <- shiny::reactive({
    res <- data |>
      filterData("summarise_observation_period", input) |>
      omopgenerics::addSettings() |>
      omopgenerics::splitAll() |>
      dplyr::select(!"result_id")

    # columns to eliminate
    colsEliminate <- colnames(res)
    colsEliminate <- colsEliminate[!colsEliminate %in% c(
      input$summarise_observation_period_tidy_columns, "variable_name", "variable_level",
      "estimate_name", "estimate_type", "estimate_value"
    )]

    # pivot
    pivot <- input$summarise_observation_period_tidy_pivot
    if (pivot != "none") {
      vars <- switch(pivot,
        "estimates" = "estimate_name",
        "estimates and variables" = c("variable_name", "variable_level", "estimate_name")
      )
      res <- res |>
        visOmopResults::pivotEstimates(pivotEstimatesBy = vars)
    }

    res |>
      dplyr::select(!dplyr::all_of(colsEliminate))
  })
  output$summarise_observation_period_tidy <- DT::renderDT({
    DT::datatable(
      getTidyDataSummariseObservationPeriod(),
      options = list(scrollX = TRUE),
      rownames = FALSE
    )
  })
  output$summarise_observation_period_tidy_download <- shiny::downloadHandler(
    filename = "tidy_summarise_observation_period.csv",
    content = function(file) {
      getTidyDataSummariseObservationPeriod() |>
        readr::write_csv(file = file)
    }
  )
  ## output summarise_observation_period -----
  ## output 15 -----
  createOutput15 <- shiny::reactive({
    result <- data |>
      filterData("summarise_observation_period", input)
    OmopSketch::tableObservationPeriod(
      result
    )
  })
  output$summarise_observation_period_gt_15 <- gt::render_gt({
    createOutput15()
  })
  output$summarise_observation_period_gt_15_download <- shiny::downloadHandler(
    filename = paste0("output_gt_summarise_observation_period.", input$summarise_observation_period_gt_15_download_type),
    content = function(file) {
      obj <- createOutput15()
      gt::gtsave(data = obj, filename = file)
    }
  )

  ## output 16 -----
  createOutput16 <- shiny::reactive({
    result <- data |>
      filterData("summarise_observation_period", input)
    result <- result |> dplyr::filter(.data$variable_name == input$summarise_observation_period_ggplot2_16_variableName)
    OmopSketch::plotObservationPeriod(
      result,
      variableName = input$summarise_observation_period_ggplot2_16_variableName,
      plotType = input$summarise_observation_period_ggplot2_16_plotType,
      facet = input$summarise_observation_period_ggplot2_16_facet, 
      colour = input$summarise_observation_period_ggplot2_16_colour
    )
  })
  output$summarise_observation_period_ggplot2_16 <- shiny::renderPlot({
    createOutput16()
  })
  output$summarise_observation_period_ggplot2_16_download <- shiny::downloadHandler(
    filename = paste0("output_ggplot2_summarise_observation_period.", "png"),
    content = function(file) {
      obj <- createOutput16()
      ggplot2::ggsave(
        filename = file,
        plot = obj,
        width = as.numeric(input$summarise_observation_period_ggplot2_16_download_width),
        height = as.numeric(input$summarise_observation_period_ggplot2_16_download_height),
        units = input$summarise_observation_period_ggplot2_16_download_units,
        dpi = as.numeric(input$summarise_observation_period_ggplot2_16_download_dpi)
      )
    }
  )
}
