# Generated by OmopViewer 0.1.0
# Be careful editing this file

ui <- bslib::page_navbar(
  title = shiny::tags$span(
    shiny::tags$img(
      src = "hdruk_logo.svg",
      width = "auto",
      height = "46px",
      class = "me-3",
      alt = "logo"
    ),
    ""
  ),
  bslib::nav_panel(
    title = "Background",
    icon = shiny::icon("disease"),
    OmopViewer::cardFromMd("background.md")
  ),
  bslib::nav_panel(
    title = "Summary",
    icon = shiny::icon("file-alt"),
    div(
      OmopViewer::cardSummary(omopgenerics::bind(cdm_snapshot,summarised_clinical_records, summarised_record_counts, summarised_in_observation, summarised_observation_period))

    )
    
  ),
  bslib::nav_panel(
    title = "Snapshot",
    icon = shiny::icon("clipboard-list"),
    bslib::layout_sidebar(
      sidebar = bslib::sidebar(
        bslib::accordion(
          bslib::accordion_panel(
            title = "Information",
            icon = shiny::icon("info"),
            shiny::p("")
          ),
          bslib::accordion_panel(
            title = "grouping",
            shiny::selectizeInput(
              inputId = "summarise_omop_snapshot_grouping_cdm_name",
              label = "Cdm name",
              choices = NULL,
              selected = NULL,
              multiple = TRUE,
              options = list(plugins = "remove_button")
            )
          ),
          bslib::accordion_panel(
            title = "Variables",
            shiny::selectizeInput(
              inputId = "summarise_omop_snapshot_variable_name",
              label = "Variable name",
              choices = NULL,
              selected = NULL,
              multiple = TRUE,
              options = list(plugins = "remove_button")
            )
          ),
          bslib::accordion_panel(
            title = "Estimates",
            shiny::selectizeInput(
              inputId = "summarise_omop_snapshot_estimate_name",
              label = "Estimate name",
              choices = NULL,
              selected = NULL,
              multiple = TRUE,
              options = list(plugins = "remove_button")
            )
          )
        )
      ),
      bslib::navset_card_tab(
        bslib::nav_panel(
          title = "Tidy",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shiny::downloadButton(outputId = "summarise_omop_snapshot_tidy_download", label = "Download csv")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                shiny::selectizeInput(
                  inputId = "summarise_omop_snapshot_tidy_columns",
                  label = "Columns",
                  choices = NULL,
                  selected = NULL,
                  multiple = TRUE,
                  options = list(plugins = "remove_button")
                ),
                shiny::radioButtons(
                  inputId = "summarise_omop_snapshot_tidy_pivot",
                  label = "Pivot estimates/variables",
                  choices = c("none", "estimates", "estimates and variables"),
                  selected = "none"
                ),
                position = "right"
              ),
              DT::dataTableOutput("summarise_omop_snapshot_tidy")
            )
          )
        ),
        bslib::nav_panel(
          title = "Snapshot table",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shiny::selectizeInput(
                  inputId = "summarise_omop_snapshot_gt_17_download_type",
                  label = "File type",
                  selected = "docx",
                  choices = c("docx", "png", "pdf", "html"),
                  multiple = FALSE
                ),
                shiny::downloadButton(outputId = "summarise_omop_snapshot_gt_17_download", label = "Download")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(,
                position = "right"
              ),
              gt::gt_output("summarise_omop_snapshot_gt_17")
            )
          )
        )
      )
    )
  ),
  bslib::nav_panel(
    title = "Cohort characteristics",
    icon = shiny::icon("users-gear"),
    bslib::layout_sidebar(
      sidebar = bslib::sidebar(
        bslib::accordion(
          bslib::accordion_panel(
            title = "Information",
            icon = shiny::icon("info"),
            shiny::p("")
          ),
          bslib::accordion_panel(
            title = "Settings",
            shiny::selectizeInput(
              inputId = "summarise_characteristics_settings_table_name",
              label = "Table name",
              choices = NULL,
              selected = NULL,
              multiple = TRUE,
              options = list(plugins = "remove_button")
            )
          ),
          bslib::accordion_panel(
            title = "grouping",
            shiny::selectizeInput(
              inputId = "summarise_characteristics_grouping_cdm_name",
              label = "Cdm name",
              choices = NULL,
              selected = NULL,
              multiple = TRUE,
              options = list(plugins = "remove_button")
            ),
            shiny::selectizeInput(
              inputId = "summarise_characteristics_grouping_cohort_name",
              label = "Cohort name",
              choices = NULL,
              selected = NULL,
              multiple = TRUE,
              options = list(plugins = "remove_button")
            ),
            shiny::selectizeInput(
              inputId = "summarise_characteristics_grouping_sex",
              label = "Sex",
              choices = NULL,
              selected = NULL,
              multiple = TRUE,
              options = list(plugins = "remove_button")
            ),
            shiny::selectizeInput(
              inputId = "summarise_characteristics_grouping_age_group",
              label = "Age group",
              choices = NULL,
              selected = NULL,
              multiple = TRUE,
              options = list(plugins = "remove_button")
            )
          ),
          bslib::accordion_panel(
            title = "Variables",
            shiny::selectizeInput(
              inputId = "summarise_characteristics_variable_name",
              label = "Variable name",
              choices = NULL,
              selected = NULL,
              multiple = TRUE,
              options = list(plugins = "remove_button")
            )
          ),
          bslib::accordion_panel(
            title = "Estimates",
            shiny::selectizeInput(
              inputId = "summarise_characteristics_estimate_name",
              label = "Estimate name",
              choices = NULL,
              selected = NULL,
              multiple = TRUE,
              options = list(plugins = "remove_button")
            )
          )
        )
      ),
      bslib::navset_card_tab(
        bslib::nav_panel(
          title = "Tidy",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shiny::downloadButton(outputId = "summarise_characteristics_tidy_download", label = "Download csv")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                shiny::selectizeInput(
                  inputId = "summarise_characteristics_tidy_columns",
                  label = "Columns",
                  choices = NULL,
                  selected = NULL,
                  multiple = TRUE,
                  options = list(plugins = "remove_button")
                ),
                shiny::radioButtons(
                  inputId = "summarise_characteristics_tidy_pivot",
                  label = "Pivot estimates/variables",
                  choices = c("none", "estimates", "estimates and variables"),
                  selected = "none"
                ),
                position = "right"
              ),
              DT::dataTableOutput("summarise_characteristics_tidy")
            )
          )
        ),
        bslib::nav_panel(
          title = "Table cohort characteristics",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shiny::selectizeInput(
                  inputId = "summarise_characteristics_gt_7_download_type",
                  label = "File type",
                  selected = "docx",
                  choices = c("docx", "png", "pdf", "html"),
                  multiple = FALSE
                ),
                shiny::downloadButton(outputId = "summarise_characteristics_gt_7_download", label = "Download")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                sortable::bucket_list(
                  header = NULL,
                  sortable::add_rank_list(
                    text = "none",
                    labels = c("sex", "age_group", "variable_name", "variable_level", "estimate_name"),
                    input_id = "summarise_characteristics_gt_7_none"
                  ),
                  sortable::add_rank_list(
                    text = "header",
                    labels = c("cdm_name", "cohort_name"),
                    input_id = "summarise_characteristics_gt_7_header"
                  ),
                  sortable::add_rank_list(
                    text = "groupColumn",
                    labels = NULL,
                    input_id = "summarise_characteristics_gt_7_groupColumn"
                  ),
                  sortable::add_rank_list(
                    text = "hide",
                    labels = character(),
                    input_id = "summarise_characteristics_gt_7_hide"
                  )
                ),
                position = "right"
              ),
              gt::gt_output("summarise_characteristics_gt_7")
            )
          )
        ),
        bslib::nav_panel(
          title = "Plot characteristics",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shiny::numericInput(
                  inputId = "summarise_characteristics_ggplot2_8_download_width",
                  label = "Width",
                  value = 15
                ),
                shiny::numericInput(
                  inputId = "summarise_characteristics_ggplot2_8_download_height",
                  label = "Height",
                  value = 10
                ),
                shiny::selectizeInput(
                  inputId = "summarise_characteristics_ggplot2_8_download_units",
                  label = "Units",
                  selected = "cm",
                  choices = c("px", "cm", "inch"),
                  multiple = FALSE
                ),
                shiny::numericInput(
                  inputId = "summarise_characteristics_ggplot2_8_download_dpi",
                  label = "dpi",
                  value = 300
                ),
                shiny::downloadButton(outputId = "summarise_characteristics_ggplot2_8_download", label = "Download")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                shiny::selectizeInput(
                  inputId = "summarise_characteristics_ggplot2_8_plotType",
                  label = "plotType",
                  selected = "barplot",
                  multiple = FALSE,
                  choices = c("boxplot", "barplot", "scatterplot"),
                  options = list(plugins = "remove_button")
                ),
                shiny::selectizeInput(
                  inputId = "summarise_characteristics_ggplot2_8_facet",
                  label = "facet",
                  selected = NULL,
                  multiple = TRUE,
                  choices = c("cdm_name", "cohort_name", "sex", "age_group", "variable_name", "variable_level", "estimate_name", "table_name"),
                  options = list(plugins = "remove_button")
                ),
                shiny::selectizeInput(
                  inputId = "summarise_characteristics_ggplot2_8_colour",
                  label = "colour",
                  selected = NULL,
                  multiple = TRUE,
                  choices = c("cdm_name", "cohort_name", "sex", "age_group", "variable_name", "variable_level", "estimate_name", "table_name"),
                  options = list(plugins = "remove_button")
                ),
                position = "right"
              ),
              shiny::plotOutput("summarise_characteristics_ggplot2_8")
            )
          )
        )
      )
    )
  ),
  bslib::nav_panel(
    title = "Summarise clinical records",
    icon = shiny::icon("clipboard-list"),
    bslib::layout_sidebar(
      sidebar = bslib::sidebar(
        bslib::accordion(
          bslib::accordion_panel(
            title = "Information",
            icon = shiny::icon("info"),
            shiny::p("")
          ),
          bslib::accordion_panel(
            title = "grouping",
            shiny::selectizeInput(
              inputId = "summarise_clinical_records_grouping_cdm_name",
              label = "Cdm name",
              choices = NULL,
              selected = NULL,
              multiple = TRUE,
              options = list(plugins = "remove_button")
            ),
            shiny::selectizeInput(
              inputId = "summarise_clinical_records_grouping_omop_table",
              label = "Omop table",
              choices = NULL,
              selected = NULL,
              multiple = TRUE,
              options = list(plugins = "remove_button")
            ),
            shiny::selectizeInput(
              inputId = "summarise_clinical_records_grouping_age_group",
              label = "Age group",
              choices = NULL,
              selected = NULL,
              multiple = TRUE,
              options = list(plugins = "remove_button")
            ),
            shiny::selectizeInput(
              inputId = "summarise_clinical_records_grouping_sex",
              label = "Sex",
              choices = NULL,
              selected = NULL,
              multiple = TRUE,
              options = list(plugins = "remove_button")
            )
          ),
          bslib::accordion_panel(
            title = "Variables",
            shiny::selectizeInput(
              inputId = "summarise_clinical_records_variable_name",
              label = "Variable name",
              choices = NULL,
              selected = NULL,
              multiple = TRUE,
              options = list(plugins = "remove_button")
            )
          ),
          bslib::accordion_panel(
            title = "Estimates",
            shiny::selectizeInput(
              inputId = "summarise_clinical_records_estimate_name",
              label = "Estimate name",
              choices = NULL,
              selected = NULL,
              multiple = TRUE,
              options = list(plugins = "remove_button")
            )
          )
        )
      ),
      bslib::navset_card_tab(
        bslib::nav_panel(
          title = "Tidy",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shiny::downloadButton(outputId = "summarise_clinical_records_tidy_download", label = "Download csv")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                shiny::selectizeInput(
                  inputId = "summarise_clinical_records_tidy_columns",
                  label = "Columns",
                  choices = NULL,
                  selected = NULL,
                  multiple = TRUE,
                  options = list(plugins = "remove_button")
                ),
                shiny::radioButtons(
                  inputId = "summarise_clinical_records_tidy_pivot",
                  label = "Pivot estimates/variables",
                  choices = c("none", "estimates", "estimates and variables"),
                  selected = "none"
                ),
                position = "right"
              ),
              DT::dataTableOutput("summarise_clinical_records_tidy")
            )
          )
        ),
        bslib::nav_panel(
          title = "Formatted",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shiny::selectizeInput(
                  inputId = "summarise_clinical_records_gt_0_download_type",
                  label = "File type",
                  selected = "docx",
                  choices = c("docx", "png", "pdf", "html"),
                  multiple = FALSE
                ),
                shiny::downloadButton(outputId = "summarise_clinical_records_gt_0_download", label = "Download")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                sortable::bucket_list(
                  header = NULL,
                  sortable::add_rank_list(
                    text = "none",
                    labels = c("omop_table", "age_group", "sex", "variable_name", "variable_level", "estimate_name"),
                    input_id = "summarise_clinical_records_gt_0_none"
                  ),
                  sortable::add_rank_list(
                    text = "header",
                    labels = "cdm_name",
                    input_id = "summarise_clinical_records_gt_0_header"
                  ),
                  sortable::add_rank_list(
                    text = "group",
                    labels = character(),
                    input_id = "summarise_clinical_records_gt_0_group"
                  ),
                  sortable::add_rank_list(
                    text = "hide",
                    labels = character(),
                    input_id = "summarise_clinical_records_gt_0_hide"
                  )
                ),
                position = "right"
              ),
              gt::gt_output("summarise_clinical_records_gt_0")
            )
          )
        ),
        bslib::nav_panel(
          title = "Table clinical records",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shiny::selectizeInput(
                  inputId = "summarise_clinical_records_gt_15_download_type",
                  label = "File type",
                  selected = "docx",
                  choices = c("docx", "png", "pdf", "html"),
                  multiple = FALSE
                ),
                shiny::downloadButton(outputId = "summarise_clinical_records_gt_15_download", label = "Download")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                position = "right"
              ),
              gt::gt_output("summarise_clinical_records_gt_15")
            )
          )
        )
      )
    )
  ),
  bslib::nav_panel(
    title = "Summarise record count",
    icon = shiny::icon("clipboard-list"),
    bslib::layout_sidebar(
      sidebar = bslib::sidebar(
        bslib::accordion(
          bslib::accordion_panel(
            title = "Information",
            icon = shiny::icon("info"),
            shiny::p("")
          ),
          bslib::accordion_panel(
            title = "Settings",
            shiny::selectizeInput(
              inputId = "summarise_record_count_settings_unit",
              label = "Unit",
              choices = NULL,
              selected = NULL,
              multiple = TRUE,
              options = list(plugins = "remove_button")
            ),
            shiny::selectizeInput(
              inputId = "summarise_record_count_settings_unitInterval",
              label = "Unitinterval",
              choices = NULL,
              selected = NULL,
              multiple = TRUE,
              options = list(plugins = "remove_button")
            )
          ),
          bslib::accordion_panel(
            title = "Grouping",
            shiny::selectizeInput(
              inputId = "summarise_record_count_grouping_cdm_name",
              label = "Cdm name",
              choices = NULL,
              selected = NULL,
              multiple = TRUE,
              options = list(plugins = "remove_button")
            ),
            shiny::selectizeInput(
              inputId = "summarise_record_count_grouping_omop_table",
              label = "Omop table",
              choices = NULL,
              selected = NULL,
              multiple = TRUE,
              options = list(plugins = "remove_button")
            ),
            shiny::selectizeInput(
              inputId = "summarise_record_count_grouping_age_group",
              label = "Age group",
              choices = NULL,
              selected = NULL,
              multiple = TRUE,
              options = list(plugins = "remove_button")
            ),
            shiny::selectizeInput(
              inputId = "summarise_record_count_grouping_sex",
              label = "Sex",
              choices = NULL,
              selected = NULL,
              multiple = TRUE,
              options = list(plugins = "remove_button")
            ),
            shiny::selectizeInput(
              inputId = "summarise_record_count_grouping_time_interval",
              label = "Time interval",
              choices = NULL,
              selected = NULL,
              multiple = TRUE,
              options = list(plugins = "remove_button")
            )
          ),
          bslib::accordion_panel(
            title = "Variables",
            shiny::selectizeInput(
              inputId = "summarise_record_count_variable_name",
              label = "Variable name",
              choices = NULL,
              selected = NULL,
              multiple = TRUE,
              options = list(plugins = "remove_button")
            )
          ),
          bslib::accordion_panel(
            title = "Estimates",
            shiny::selectizeInput(
              inputId = "summarise_record_count_estimate_name",
              label = "Estimate name",
              choices = NULL,
              selected = NULL,
              multiple = TRUE,
              options = list(plugins = "remove_button")
            )
          )
        )
      ),
      bslib::navset_card_tab(
        bslib::nav_panel(
          title = "Tidy",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shiny::downloadButton(outputId = "summarise_record_count_tidy_download", label = "Download csv")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                shiny::selectizeInput(
                  inputId = "summarise_record_count_tidy_columns",
                  label = "Columns",
                  choices = NULL,
                  selected = NULL,
                  multiple = TRUE,
                  options = list(plugins = "remove_button")
                ),
                shiny::radioButtons(
                  inputId = "summarise_record_count_tidy_pivot",
                  label = "Pivot estimates/variables",
                  choices = c("none", "estimates", "estimates and variables"),
                  selected = "none"
                ),
                position = "right"
              ),
              DT::dataTableOutput("summarise_record_count_tidy")
            )
          )
        ),
        bslib::nav_panel(
          title = "Formatted",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shiny::selectizeInput(
                  inputId = "summarise_record_count_gt_0_download_type",
                  label = "File type",
                  selected = "docx",
                  choices = c("docx", "png", "pdf", "html"),
                  multiple = FALSE
                ),
                shiny::downloadButton(outputId = "summarise_record_count_gt_0_download", label = "Download")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                sortable::bucket_list(
                  header = NULL,
                  sortable::add_rank_list(
                    text = "none",
                    labels = c("omop_table", "age_group", "sex", "time_interval", "variable_name", "variable_level", "estimate_name", "unit", "unitInterval"),
                    input_id = "summarise_record_count_gt_0_none"
                  ),
                  sortable::add_rank_list(
                    text = "header",
                    labels = "cdm_name",
                    input_id = "summarise_record_count_gt_0_header"
                  ),
                  sortable::add_rank_list(
                    text = "group",
                    labels = character(),
                    input_id = "summarise_record_count_gt_0_group"
                  ),
                  sortable::add_rank_list(
                    text = "hide",
                    labels = character(),
                    input_id = "summarise_record_count_gt_0_hide"
                  )
                ),
                position = "right"
              ),
              gt::gt_output("summarise_record_count_gt_0")
            )
          )
        ),
        bslib::nav_panel(
          title = "Plot record count",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shiny::numericInput(
                  inputId = "summarise_record_count_ggplot2_16_download_width",
                  label = "Width",
                  value = 15
                ),
                shiny::numericInput(
                  inputId = "summarise_record_count_ggplot2_16_download_height",
                  label = "Height",
                  value = 10
                ),
                shiny::selectizeInput(
                  inputId = "summarise_record_count_ggplot2_16_download_units",
                  label = "Units",
                  selected = "cm",
                  choices = c("px", "cm", "inch"),
                  multiple = FALSE
                ),
                shiny::numericInput(
                  inputId = "summarise_record_count_ggplot2_16_download_dpi",
                  label = "dpi",
                  value = 300
                ),
                shiny::downloadButton(outputId = "summarise_record_count_ggplot2_16_download", label = "Download")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                shiny::selectizeInput(
                  inputId = "summarise_record_count_ggplot2_16_colour",
                  label = "Colour",
                  selected = "cdm_name",
                  multiple = TRUE,
                  choices = c("cdm_name", "age_group", "sex"),
                  options = list(plugins = "remove_button")
                ),
                shiny::selectizeInput(
                  inputId = "summarise_record_count_ggplot2_16_facet",
                  label = "Facet",
                  selected = "cdm_name",
                  multiple = TRUE,
                  choices = c("cdm_name", "age_group", "sex"),
                  options = list(plugins = "remove_button")
                ),
                position = "right"
              ),
              shiny::plotOutput("summarise_record_count_ggplot2_16")
            )
          )
        )
      )
    )
  ),
  bslib::nav_panel(
    title = "Summarise in observation",
    icon = shiny::icon("clipboard-list"),
    
    bslib::layout_sidebar(
      sidebar = bslib::sidebar(
        bslib::accordion(
          bslib::accordion_panel(
            title = "Information",
            icon = shiny::icon("info"),
            shiny::p("")
          ),
          bslib::accordion_panel(
            title = "Settings",
            shiny::selectizeInput(
              inputId = "summarise_in_observation_settings_unit",
              label = "Unit",
              choices = NULL,
              selected = NULL,
              multiple = TRUE,
              options = list(plugins = "remove_button")
            ),
            shiny::selectizeInput(
              inputId = "summarise_in_observation_settings_unitInterval",
              label = "Unitinterval",
              choices = NULL,
              selected = NULL,
              multiple = TRUE,
              options = list(plugins = "remove_button")
            )
          ),
          bslib::accordion_panel(
            title = "Grouping",
            shiny::selectizeInput(
              inputId = "summarise_in_observation_grouping_cdm_name",
              label = "CDM Name",
              choices = NULL,
              selected = NULL,
              multiple = TRUE,
              options = list(plugins = "remove_button")
            ),
            shiny::selectizeInput(
              inputId = "summarise_in_observation_grouping_omop_table",
              label = "OMOP Table",
              choices = NULL,
              selected = NULL,
              multiple = TRUE,
              options = list(plugins = "remove_button")
            ),
            shiny::selectizeInput(
              inputId = "summarise_in_observation_grouping_sex",
              label = "Sex",
              choices = NULL,
              selected = NULL,
              multiple = TRUE,
              options = list(plugins = "remove_button")
            ),
            shiny::selectizeInput(
              inputId = "summarise_in_observation_grouping_age_group",
              label = "Age Group",
              choices = NULL,
              selected = NULL,
              multiple = TRUE,
              options = list(plugins = "remove_button")
            )
          ),
          bslib::accordion_panel(
            title = "Variables",
            shiny::selectizeInput(
              inputId = "summarise_in_observation_variable_name",
              label = "Variable Name",
              choices = NULL,
              selected = NULL,
              multiple = TRUE,
              options = list(plugins = "remove_button")
            )
          ),
          bslib::accordion_panel(
            title = "Estimates",
            shiny::selectizeInput(
              inputId = "summarise_in_observation_estimate_name",
              label = "Estimate Name",
              choices = NULL,
              selected = NULL,
              multiple = TRUE,
              options = list(plugins = "remove_button")
            )
          )
        )
      ),
      
      bslib::navset_card_tab(
        bslib::nav_panel(
          title = "Tidy",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shiny::downloadButton(
                  outputId = "summarise_in_observation_tidy_download",
                  label = "Download CSV"
                )
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                shiny::selectizeInput(
                  inputId = "summarise_in_observation_tidy_columns",
                  label = "Columns",
                  choices = NULL,
                  selected = NULL,
                  multiple = TRUE,
                  options = list(plugins = "remove_button")
                ),
                shiny::radioButtons(
                  inputId = "summarise_in_observation_tidy_pivot",
                  label = "Pivot estimates/variables",
                  choices = c("none", "estimates", "estimates and variables"),
                  selected = "none"
                ),
                position = "right"
              ),
              DT::dataTableOutput("summarise_in_observation_tidy")
            )
          )
        ),
        
        bslib::nav_panel(
          title = "Formatted",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shiny::selectizeInput(
                  inputId = "summarise_in_observation_gt_0_download_type",
                  label = "File Type",
                  selected = "docx",
                  choices = c("docx", "png", "pdf", "html"),
                  multiple = FALSE
                ),
                shiny::downloadButton(
                  outputId = "summarise_in_observation_gt_0_download",
                  label = "Download"
                )
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                sortable::bucket_list(
                  header = NULL,
                  sortable::add_rank_list(
                    text = "none",
                    labels = c("omop_table", "sex", "age_group", "variable_name", "variable_level", "estimate_name", "unit", "unitInterval"),
                    input_id = "summarise_in_observation_gt_0_none"
                  ),
                  sortable::add_rank_list(
                    text = "header",
                    labels = "cdm_name",
                    input_id = "summarise_in_observation_gt_0_header"
                  ),
                  sortable::add_rank_list(
                    text = "group",
                    labels = character(),
                    input_id = "summarise_in_observation_gt_0_group"
                  ),
                  sortable::add_rank_list(
                    text = "hide",
                    labels = character(),
                    input_id = "summarise_in_observation_gt_0_hide"
                  )
                ),
                position = "right"
              ),
              gt::gt_output("summarise_in_observation_gt_0")
            )
          )
        ),
        
        bslib::nav_panel(
          title = "Plot in Observation",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shiny::numericInput(
                  inputId = "summarise_in_observation_ggplot2_19_download_width",
                  label = "Width",
                  value = 15
                ),
                shiny::numericInput(
                  inputId = "summarise_in_observation_ggplot2_19_download_height",
                  label = "Height",
                  value = 10
                ),
                shiny::selectizeInput(
                  inputId = "summarise_in_observation_ggplot2_19_download_units",
                  label = "Units",
                  selected = "cm",
                  choices = c("px", "cm", "inch"),
                  multiple = FALSE
                ),
                shiny::numericInput(
                  inputId = "summarise_in_observation_ggplot2_19_download_dpi",
                  label = "DPI",
                  value = 300
                ),
                shiny::downloadButton(
                  outputId = "summarise_in_observation_ggplot2_19_download",
                  label = "Download"
                )
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                shiny::selectizeInput(
                  inputId = "summarise_in_observation_ggplot2_19_colour",
                  label = "Colour",
                  selected = "cdm_name",
                  multiple = TRUE,
                  choices = c("cdm_name","sex", "age_group", "variable_name"  ),
                  options = list(plugins = "remove_button")
                ),
                shiny::selectizeInput(
                  inputId = "summarise_in_observation_ggplot2_19_facet",
                  label = "Facet",
                  selected =  "variable_name",
                  multiple = TRUE,
                  choices = c("cdm_name","sex", "age_group", "variable_name"),
                  options = list(plugins = "remove_button")
                ),
                position = "right"
              ),
              shiny::plotOutput("summarise_in_observation_ggplot2_19")
            )
          )
        )
      )
    )
  ),
      

  bslib::nav_panel(
    title = "Observation period",
    icon = shiny::icon("eye"),
    bslib::layout_sidebar(
      sidebar = bslib::sidebar(
        bslib::accordion(
          bslib::accordion_panel(
            title = "Information",
            icon = shiny::icon("info"),
            shiny::p("")
          ),
          bslib::accordion_panel(
            title = "grouping",
            shiny::selectizeInput(
              inputId = "summarise_observation_period_grouping_cdm_name",
              label = "Cdm name",
              choices = NULL,
              selected = NULL,
              multiple = TRUE,
              options = list(plugins = "remove_button")
            ),
            shiny::selectizeInput(
              inputId = "summarise_observation_period_grouping_observation_period_ordinal",
              label = "Observation period ordinal",
              choices = NULL,
              selected = NULL,
              multiple = TRUE,
              options = list(plugins = "remove_button")
            ),
            shiny::selectizeInput(
              inputId = "summarise_observation_period_grouping_age_group",
              label = "Age group",
              choices = NULL,
              selected = NULL,
              multiple = TRUE,
              options = list(plugins = "remove_button")
            ),
            shiny::selectizeInput(
              inputId = "summarise_observation_period_grouping_sex",
              label = "Sex",
              choices = NULL,
              selected = NULL,
              multiple = TRUE,
              options = list(plugins = "remove_button")
            )
          ),
          bslib::accordion_panel(
            title = "Variables",
            shiny::selectizeInput(
              inputId = "summarise_observation_period_variable_name",
              label = "Variable name",
              choices = NULL,
              selected = NULL,
              multiple = TRUE,
              options = list(plugins = "remove_button")
            )
          ),
          bslib::accordion_panel(
            title = "Estimates",
            shiny::selectizeInput(
              inputId = "summarise_observation_period_estimate_name",
              label = "Estimate name",
              choices = NULL,
              selected = NULL,
              multiple = TRUE,
              options = list(plugins = "remove_button")
            )
          )
        )
      ),
      bslib::navset_card_tab(
        bslib::nav_panel(
          title = "Tidy",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shiny::downloadButton(outputId = "summarise_observation_period_tidy_download", label = "Download csv")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                shiny::selectizeInput(
                  inputId = "summarise_observation_period_tidy_columns",
                  label = "Columns",
                  choices = NULL,
                  selected = NULL,
                  multiple = TRUE,
                  options = list(plugins = "remove_button")
                ),
                shiny::radioButtons(
                  inputId = "summarise_observation_period_tidy_pivot",
                  label = "Pivot estimates/variables",
                  choices = c("none", "estimates", "estimates and variables"),
                  selected = "none"
                ),
                position = "right"
              ),
              DT::dataTableOutput("summarise_observation_period_tidy")
            )
          )
        ),
        bslib::nav_panel(
          title = "Table observation period",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shiny::selectizeInput(
                  inputId = "summarise_observation_period_gt_15_download_type",
                  label = "File type",
                  selected = "docx",
                  choices = c("docx", "png", "pdf", "html"),
                  multiple = FALSE
                ),
                shiny::downloadButton(outputId = "summarise_observation_period_gt_15_download", label = "Download")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(,
                                       position = "right"
              ),
              gt::gt_output("summarise_observation_period_gt_15")
            )
          )
        ),
        bslib::nav_panel(
          title = "Plot observation period",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shiny::numericInput(
                  inputId = "summarise_observation_period_ggplot2_16_download_width",
                  label = "Width",
                  value = 15
                ),
                shiny::numericInput(
                  inputId = "summarise_observation_period_ggplot2_16_download_height",
                  label = "Height",
                  value = 10
                ),
                shiny::selectizeInput(
                  inputId = "summarise_observation_period_ggplot2_16_download_units",
                  label = "Units",
                  selected = "cm",
                  choices = c("px", "cm", "inch"),
                  multiple = FALSE
                ),
                shiny::numericInput(
                  inputId = "summarise_observation_period_ggplot2_16_download_dpi",
                  label = "dpi",
                  value = 300
                ),
                shiny::downloadButton(outputId = "summarise_observation_period_ggplot2_16_download", label = "Download")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                shiny::selectizeInput(
                  inputId = "summarise_observation_period_ggplot2_16_variableName",
                  label = "variableName",
                  selected = "number subjects",
                  multiple = ,
                  choices = c("number subjects", "records per person", "duration in days", "days to next observation period"),
                  options = list(plugins = "remove_button")
                ),
                shiny::selectizeInput(
                  inputId = "summarise_observation_period_ggplot2_16_plotType",
                  label = "plotType",
                  selected = "barplot",
                  multiple = ,
                  choices = c("barplot", "boxplot", "densityplot"),
                  options = list(plugins = "remove_button")
                ),
                shiny::selectizeInput(
                  inputId = "summarise_observation_period_ggplot2_16_facet",
                  label = "facet",
                  selected = "cdm_name",
                  multiple = TRUE,
                  choices = c("cdm_name", "observation_period_ordinal", "age_group", "sex"),
                  options = list(plugins = "remove_button")
                ),
                position = "right"
              ),
              shiny::plotOutput("summarise_observation_period_ggplot2_16")
            )
          )
        )
      )
    )
  ),
  bslib::nav_spacer(),
  bslib::nav_item(
    bslib::popover(
      shiny::icon("download"),
      shiny::downloadButton(
        outputId = "download_raw",
        label = "Download raw data",
        icon = shiny::icon("download")
      )
    )
  ),
  bslib::nav_item(
    bslib::popover(
      shiny::icon("circle-info"),
      shiny::tags$img(
        src = "hds_logo.svg",
        class = "logo-img",
        alt = "Logo",
        height = "auto",
        width = "30%",
        style = "float:right"
      ),
      "This shiny app was generated with ",
      shiny::a(
        "OmopViewer",
        href = "https://github.com/OHDSI/OmopViewer",
        target = "_blank"
      ),
      shiny::strong("v0.1.0")
    )
  ),
  bslib::nav_item(bslib::input_dark_mode(id = "dark_mode", mode = "light"))
)
