# Generated by OmopViewer 0.1.0
# Be careful editing this file

library(bslib)
library(dplyr)
library(DT)
library(gt)
library(here)
library(OmopSketch)
library(OmopViewer)
library(readr)
library(shiny)
library(visOmopResults)

data <- OmopViewer::importSummarisedResult(here::here("data")) |>
  OmopViewer::correctSettings()
