# Generated by OmopViewer 0.1.0
# Be careful editing this file

ui <- bslib::page_navbar(
  title = shiny::tags$span(
    shiny::tags$img(
      src = "ohdsi_logo.svg",
      width = "auto",
      height = "46px",
      class = "me-3",
      alt = "logo"
    ),
    "snapshot_cprd100k"
  ),
  bslib::nav_panel(
    title = "Background",
    icon = shiny::icon("disease"),
    OmopViewer::cardFromMd("background.md")
  ),
  bslib::nav_panel(
    title = "Summary",
    icon = shiny::icon("file-alt"),
    OmopViewer::cardSummary(data)
  ),
  bslib::nav_panel(
    title = "Snapshot",
    icon = shiny::icon("clipboard-list"),
    bslib::layout_sidebar(
      sidebar = bslib::sidebar(
        bslib::accordion(
          bslib::accordion_panel(
            title = "Information",
            icon = shiny::icon("info"),
            shiny::p("")
          ),
          bslib::accordion_panel(
            title = "grouping",
            shiny::selectizeInput(
              inputId = "summarise_omop_snapshot_grouping_cdm_name",
              label = "Cdm name",
              choices = NULL,
              selected = NULL,
              multiple = TRUE,
              options = list(plugins = "remove_button")
            )
          ),
          bslib::accordion_panel(
            title = "Variables",
            shiny::selectizeInput(
              inputId = "summarise_omop_snapshot_variable_name",
              label = "Variable name",
              choices = NULL,
              selected = NULL,
              multiple = TRUE,
              options = list(plugins = "remove_button")
            )
          ),
          bslib::accordion_panel(
            title = "Estimates",
            shiny::selectizeInput(
              inputId = "summarise_omop_snapshot_estimate_name",
              label = "Estimate name",
              choices = NULL,
              selected = NULL,
              multiple = TRUE,
              options = list(plugins = "remove_button")
            )
          )
        )
      ),
      bslib::navset_card_tab(
        bslib::nav_panel(
          title = "Tidy",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shiny::downloadButton(outputId = "summarise_omop_snapshot_tidy_download", label = "Download csv")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                shiny::selectizeInput(
                  inputId = "summarise_omop_snapshot_tidy_columns",
                  label = "Columns",
                  choices = NULL,
                  selected = NULL,
                  multiple = TRUE,
                  options = list(plugins = "remove_button")
                ),
                shiny::radioButtons(
                  inputId = "summarise_omop_snapshot_tidy_pivot",
                  label = "Pivot estimates/variables",
                  choices = c("none", "estimates", "estimates and variables"),
                  selected = "none"
                ),
                position = "right"
              ),
              DT::dataTableOutput("summarise_omop_snapshot_tidy")
            )
          )
        ),
        bslib::nav_panel(
          title = "Snapshot table",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shiny::selectizeInput(
                  inputId = "summarise_omop_snapshot_gt_17_download_type",
                  label = "File type",
                  selected = "docx",
                  choices = c("docx", "png", "pdf", "html"),
                  multiple = FALSE
                ),
                shiny::downloadButton(outputId = "summarise_omop_snapshot_gt_17_download", label = "Download")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(,
                position = "right"
              ),
              gt::gt_output("summarise_omop_snapshot_gt_17")
            )
          )
        )
      )
    )
  ),
  bslib::nav_spacer(),
  bslib::nav_item(
    bslib::popover(
      shiny::icon("download"),
      shiny::downloadButton(
        outputId = "download_raw",
        label = "Download raw data",
        icon = shiny::icon("download")
      )
    )
  ),
  bslib::nav_item(
    bslib::popover(
      shiny::icon("circle-info"),
      shiny::tags$img(
        src = "hds_logo.svg",
        class = "logo-img",
        alt = "Logo",
        height = "auto",
        width = "30%",
        style = "float:right"
      ),
      "This shiny app was generated with ",
      shiny::a(
        "OmopViewer",
        href = "https://github.com/OHDSI/OmopViewer",
        target = "_blank"
      ),
      shiny::strong("v0.1.0")
    )
  ),
  bslib::nav_item(bslib::input_dark_mode(id = "dark_mode", mode = "light"))
)
